AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sitio web est?tico con S3, CloudFront, WAF y API Gateway para tienda AFRORAICES'

Resources:

  # Bucket de S3 para el sitio web
  StaticSiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "afroraices-static-site"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Pol?tica p?blica para permitir acceso al contenido del bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteS3Bucket.Arn}/*"

  # Web ACL para WAF
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: StaticSiteWAF
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: StaticSiteWAFMetric
      Rules:
        - Name: BlockSpecificIPs
          Priority: 0
          Action:
            Block: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt IPSet.Arn
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockSpecificIPs

  # IPSet para bloquear direcciones espec?ficas
  IPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: BlockedIPs
      Scope: CLOUDFRONT
      IPAddressVersion: IPV4
      Addresses:
        - "192.0.2.0/24"

  # Distribuci?n de CloudFront con WAF
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        WebACLId: !GetAtt WebACL.Arn  # Usamos el ARN completo del WebACL
        Origins:
          - DomainName: !GetAtt StaticSiteS3Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig: {}
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  WebsiteURL:
    Description: "URL p?blica del archivo index.html"
    Value: !Sub "http://${StaticSiteS3Bucket.WebsiteURL}/index.html"
    Export:
      Name: WebsiteURL

  CloudFrontURL:
    Description: "URL del sitio web servido por CloudFront"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Export:
      Name: CloudFrontURL
